# Generated by Django 4.0 on 2021-12-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maqola',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
