# Generated by Django 4.0 on 2021-12-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_alter_maqola_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rasm',
            name='photo',
            field=models.FileField(upload_to='media/'),
        ),
    ]
